from enum import Enum


class AvatarColor(str, Enum):
    PASTEL_PINK = '#FFB5A7'
    PASTEL_PEACH = '#FCD5CE'
    PASTEL_LAVENDER = '#F8EDEB'
    PASTEL_BEIGE = '#F9DCC4'
    PASTEL_ORANGE = '#FEC89A'
    PASTEL_SAGE = '#D8E2DC'
    PASTEL_BLUE = '#B5E2FA'


AVATAR_SIZE = 200
AVATAR_FONT_RATIO = 0.6
AVATAR_TEXT_COLOR = "#333333"

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
